Updated personal scripts

diff --git a/scripts/personal/amimnt b/scripts/personal/amimnt
--- a/scripts/personal/amimnt
+++ b/scripts/personal/amimnt
@@ -7,28 +7,34 @@ USERNAME=""
 PASSWORD=""
 MNTPOINT=/run/media/$USER/Amiga
 
-echo "Scanning subnet $SUBNET for host $HOSTNAME..."
+echo "Scanning subnet $SUBNET for host '$HOSTNAME'..."
 ADDR=$(sudo nbtscan -r 192.168.$SUBNET.0/24 -s ' ' \
-		| grep -E '.* '$HOSTNAME | cut -d ' ' -f1)
+		| grep -E ".* $HOSTNAME" | cut -d ' ' -f1)
 
-[ -n "$ADDR" ] || (echo "Unable to get address of host."; exit 1)
-
-if [ ! -d "$MNTPOINT" ]; then
-	sudo mkdir -p "$MNTPOINT" && sudo chown $USER:$USER "$MNTPOINT"
-elif mountpoint -q "$MNTPOINT"; then
-	sudo umount "$MNTPOINT"
-fi
-
-ARGS="-t cifs \
--o username='$USERNAME',password='$PASSWORD',\
-uid=$UID,gid=$UID,file_mode=0775,dir_mode=0775,\
-vers=1.0 \
-//$ADDR/$SHARENAME \
-$MNTPOINT"
-
-if [ $? == 0 ]; then
-	echo mount options: $ARGS
-	sudo mount $ARGS && echo "Mounted //$ADDR/$SHARENAME at $MNTPOINT"
+if [ -n "$ADDR" ]; then
+	echo "Found host '$HOSTNAME' at $ADDR"
+	
+	if [ ! -d "$MNTPOINT" ]; then
+		sudo mkdir -p "$MNTPOINT" && sudo chown $USER:$USER "$MNTPOINT"
+	elif mountpoint -q "$MNTPOINT"; then
+		sudo umount "$MNTPOINT"
+	fi
+	
+	if [ $? == 0 ]; then
+		ARGS=$(printf '%s' \
+			"-t cifs \
+			-o username='$USERNAME',password='$PASSWORD'," \
+			"uid=$UID,gid=$UID,file_mode=0775,dir_mode=0775," \
+			"vers=1.0 \
+			//$ADDR/$SHARENAME \
+			$MNTPOINT")
+		
+		echo mount options: $ARGS
+		sudo mount $ARGS && echo "Mounted '//$ADDR/$SHARENAME' at '$MNTPOINT'"
+	else
+		echo "Unable to create mount point"; exit $?
+	fi
 else
-	echo "Unable to create mount point"; exit $?
+	echo "Unable to find address of host."
+	exit 1
 fi
